swagger: "2.0"
info:
  title: "City API"
  version: "1.0.0"
  description: "The City API is a RESTFUL API managing Cities and their metadata with CRUD calls and persists the
  information in a postgres instance."
  contact:
    name: "Carsten Stephan"
    email: "carsten_stephan@mail.de"
paths:
  /api/city:
    get:
      summary: "Get list of cities"
      tags:
        - "City"
      responses:
        200:
          description: "Successful response"
    post:
      summary: "Create a new city"
      tags:
        - "City"
      responses:
        200:
          description: "Successful response"
  /api/city/{city_id}:
    get:
      summary: "Get information about a city"
      tags:
        - "City"
      responses:
        200:
          description: "Successful response"
    put:
      summary: "Update information about a city"
      tags:
        - "City"
      responses:
        200:
          description: "Successful response"
    delete:
      summary: "Delete a city by city_id"
      tags:
        - "City"
      responses:
        200:
          description: "Successful response"
